name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build_nds:
    name: Build NDS
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: make -f Makefile.blocksds

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uxnds (NDS)
          path: |
            LICENSE
            uxn*.nds
            uxn/

  build_3ds:
    name: Build 3DS
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build (release)
        run: make -f Makefile.3ds DEBUG=false

      - name: Build (debug)
        run: make -f Makefile.3ds DEBUG=true

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uxnds (3DS)
          path: |
            LICENSE
            uxn*.3dsx
            uxn/
